### PR TITLE
Feature/#68 frontend wireframe

### PR DESCRIPTION
**Pull request by Rafael4DC**
Hi! I want to check if the logic used, especially on the hooks folder, and the API calls on the services section make sense. You can fully ignore apiFetch, as its still 100% WIP
The rest i want to make double sure everything makes sense, as it should, from what I read

### CODE REVIEW

**Comment by Rafael4DC** [comment]
@YuriValle

**Review by YuriValle — COMMENTED** [review]
What is this branch name ? I'm still missing the wireframe.
As we've spoken, it's fine to not be eye candy, but it can't be pepper spray, either way, the most challenging thing I see here is that you're still thinking and using endpoins (which you don't have) and a RBAC.
Don't mind the user roles for now and you should be fine.

**Comment by Rafael4DC** [comment]
Added another commit, this time more relevant
Besides what's written in the commit message its important to keep in mind
I decided to use react bootstrap because its closer to how jetpack compose works, which both developers know how to use better
But regular bootstrap can still be used, wanted to mainly demo it to look for approval in its usage, from both relevant parties
@bfmserra @YuriValle

**Comment by YuriValle** [comment]
It still needs work, but it's much better now.
Checkboxes don't work as expected.

Please avoid creating thinks with 'Work In Progress'.
If you don't have it now, you don't put it, specially because it's NOT in progress, you're doing something else.

**Review by YuriValle — APPROVED** [review]

**Comment by YuriValle** [comment]
The concept of DTO does not exist in a frontend context.
This task is being developer way too far from what the scope of it was meant to be.

**Comment by YuriValle** [comment]
Whenever you're ready to stop with this task and move on to another task.
Feel free.

**Pull request merged**
